- src/utils/builder.js
- src/utils/builder.test.js
> Decode XML entities

- src/utils/builder.js
Minor modification to unescape ampersand characters in the chat message.
I am not sure if this project accept PR. If not, please ignore.
> unescaping chat message

- src/components/player.js
- src/components/presentation/canvas.js
- src/components/presentation/index.js
- src/utils/data.js
- src/utils/data.test.js
Trying to fix #26 .
Could you test these changes @hiroshisuga ?
> Clear intermediate draws

- src/components/bars/index.scss
- src/components/index.scss
- src/components/player.js
> Content fullscreen button

- src/components/loader.js
- src/components/player.js
- src/components/video/index.js
- src/utils/data.js
- src/utils/data.test.js
Closes #3.
Valid formats are:
- `t=(n)h(0-59)m(0-59)s`;
- `t=(0-59)m(0-59)s`;
- `t=(0-59)s`.
> Initial time as a query param

- src/utils/builder.js
Refactored #33 .
@hiroshisuga I rewrote your pull request. I kept the same XML identifiers from your work. Could you check if is still working as expected?
> Use updated meta record name if available

- src/components/chat/index.js
- src/components/chat/message.js
- src/utils/builder.js
Also trimming special whitespaces.
> Processing avatar initials once at data building

- src/components/index.scss
- src/components/presentation/index.scss
- src/components/thumbnails/index.scss
- src/components/utils/index.scss
- src/styles/colors.scss
Improvements for customization.
> Colors refactor

- src/components/chat/index.js
- src/components/chat/message.js
- src/components/player.js
- src/components/thumbnails/index.js
- src/utils/data.js
Navigate through chat messages and thumbnails
> Tab indexes

- README.md
- src/components/bars/action.js
- src/components/bars/navigation.js
- src/components/index.scss
- src/components/player.js
- src/styles/sizes.scss
- src/utils/data.js
Removes main buttons from the UI as a query string layout param `l=disabled`.
> Disabled layout

- src/components/loader.js
- src/components/player.js
- src/utils/builder.js
- src/utils/data.js
- src/utils/logger.js
- src/utils/monitor.js
> Include first logger version

- src/components/chat/index.scss
- src/components/player.js
- src/components/thumbnails/index.js
- src/components/thumbnails/index.scss
- src/utils/builder.js
- src/utils/data.js
- src/utils/synchronizer.js
> Screenshare thumbnail

- package-lock.json
- package.json
- src/components/chat/message.js
> React intl update

- src/components/bars/navigation.js
- src/components/more/index.js
- src/components/more/index.scss
- src/components/player.js
- src/styles/icons.scss
- src/styles/sizes.scss
- src/utils/builder.js
- src/utils/data.js
> More button first version

- src/components/presentation/canvas.js
- src/utils/builder.js
Fixes paragraph tag unwanted margins and 2.0 html injected line breaking tags
> Fix text annotation for version 2.0 recordings

- src/components/about/index.js
- src/components/chat/index.js
- src/components/chat/index.scss
- src/components/index.scss
- src/components/notes/index.js
- src/components/notes/index.scss
- src/components/player.js
- src/locales/messages/ar.json
- src/locales/messages/de.json
- src/locales/messages/en.json
- src/locales/messages/es.json
- src/locales/messages/fr.json
- src/locales/messages/it.json
- src/locales/messages/ja.json
- src/locales/messages/pt.json
- src/locales/messages/ru.json
- src/styles/icons.scss
Disabled as default since it's still missing the server side
> Shared notes UI

- README.md
- src/components/player.js
- src/config.json
- src/utils/data.js
- src/utils/shortcuts.js
Included shortcuts for the main toggle functions (fullscreen section
swap and thumbnails), video seek and slide skip.
Colses #22 and #25 .
> Add keyboard shortcuts

- src/components/player.js
Disabled layout also handles application's control header.
Closes #86 .
> Improve disabled layout

- README.md
Just an idea of showing an example of URL query string. I was trying "?t=001000"  and failed.
> example of query string in Readme

- src/components/presentation/canvas.js
- src/utils/builder.js
v2.3 polls annotations changed by removing part of the SVG elements.
This is a first move for polls to work but would be good to make some
extra effort to have this adaptations isolated from the rest of the
code in the future.
Closes #75
> First adaptation for v2.3 polls

- README.md
- src/locales/index.js
- src/utils/params.js
Locale defined at the URL query params:
- `locale=xx-XX`
> feat(params): fetch locale

- src/components/presentation/index.js
> fix(presentation): check on slide index change

- src/components/loader/data/index.scss
- src/components/loader/data/item.js
- src/components/loader/index.js
- src/components/loader/index.scss
- src/config.json
Adjust the loader's feedback on built data.
> refactor(loader): built data feedback

- src/components/bars/index.scss
- src/components/bars/top/index.scss
- src/components/chat/messages/system/index.scss
- src/components/chat/messages/system/poll/index.scss
- src/components/error/index.scss
- src/components/loader/index.scss
- src/components/player/application/index.scss
- src/components/player/index.scss
- src/components/presentation/index.scss
- src/components/utils/avatar/index.scss
- src/components/utils/button/index.scss
- src/components/utils/modal/index.scss
- src/components/webcams/index.scss
- src/index.scss
- src/styles/colors.scss
Three scopes of color patterns (primary, secondary and tertiary) named
based on their relevance at the UI:
- primary: main content
- secondary: panel and modals
- tertiary: lesser content
> refactor: UI color patterns

- README.md
- src/components/player/index.js
- src/config.json
- src/utils/actions.js
Use `Alt`+`Shift`+`Enter` to play or pause the playback.
Closes #95
> feat(shortcuts): add play/pause control

- src/components/modals/about/body/shortcuts/index.js
- src/components/modals/about/body/shortcuts/index.scss
- src/styles/sizes.scss
Control elements overflow by including a scrollable wrapper around the
shortcuts list.
> refactor(shortcuts): make list scrollable

- src/components/bars/top/buttons/search.js
- src/components/bars/top/buttons/section.js
- src/components/bars/top/buttons/swap.js
- src/config.json
- [visibility management](https://github.com/bigbluebutton/bbb-playback/commit/1c8af63882bddffd3840688420e50f8a510e4a8b)
- [remove thumbnails](https://github.com/bigbluebutton/bbb-playback/commit/fcb6825ff2a0ca5a7a422e764ab33f59b89c0173)
> fix(controls): multiple changes

- src/components/notes/index.js
Set width to the inner div that will receive the notes' HTML content.
Closes #193
> fix(notes): word wrap

- package-lock.json
- package.json
More details: https://github.com/facebook/create-react-app/issues/11174
> feat(playback): move react-scripts to devDependencies

- src/components/tldraw/index.js
See https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.0-rc.4/bigbluebutton-html5/imports/api/slides/server/helpers.js
> fix(tldraw): apply scale factor introduced in 2.6.0-rc.4

- src/components/tldraw/index.js
Reduce the maximum size of the whiteboard canvas page.
> fix(tldraw): Reduce max canvas size

- package-lock.json
- package.json
- src/components/tldraw/index.js
- src/utils/builder.js
- Check the bbb-version in the file to know which scaling is needed and react accordingly. 
- Also fixed packages vulnerabilities  with npm audit --force.
> refactor(tldraw): use bbb-version from tldraw.json if available

- src/locales/messages/ja.json
A bit more natural..
Do you still accept modifications?
> Slightly better Japanese translation
