src/components/chat/message.js

Looks like since Chrome 80 you must force `timeCycle=h23` to avoid displaying midnight as `24:00:00`. Since we localize the chat message time and force it to be something like epoch zero to higher Chrome starting zero was being displayed as `24:00:00`. It could be an easy fix if `react-intl` didn't had this issue active https://github.com/formatjs/formatjs/issues/1577.
While `FormattedTime` isn't handling `timeCycle` correctly we will be setting `Intl` manually. I'll add a new issue to track `react-intl` changes so we can update and revert this change in the future.

Workaround to render the correct chat message time

---

src/utils/data.js
src/utils/data.test.js

Replaces the current index linear O(n) search for a binary O(log n). This should improve client performance.
Closes #6.

Current index binary search

---

README.md
src/components/loader.js
src/components/presentation/canvas.js
src/components/presentation/slide.js
src/components/router.js
src/components/screenshare/index.js
src/components/thumbnails/index.js
src/components/video/index.js
src/index.js
src/utils/data.js

This adds a build option REACT_APP_NO_ROUTER that removes the code to
read the recordId from the URL. When used in combination with
PUBLIC_URL=. it will load all resources from the current directory. With
this setup, you can put the playback files and recording media files
together into a single directory for a self-contained recording.

Add support for creating self-contained recording playback packages

---

src/components/screenshare/index.js
src/components/video/index.js

The crossorigin attribute isn't required for the normal case of loading
video from the same domain. And Safari (both desktop and iOS) have a bug
when crossOrigin="anonymous" is used that cause it to remove
authentication cookies on same-origin requests! Removing the attribute
works around that issue.

Remove the crossorigin attribute on video tags

---

src/components/screenshare/index.js
src/components/video/index.js
src/utils/videojs/marker.js

Current versions of video.js include the "HTTP Streaming" plugin by
default, which adds support for HLS and DASH format videos. Since we
aren't actually using those, we can instead import only the video.js
core features.
This reduces the size of the built javascript by ~78KB with no loss of
functionality. (vtt.js is still included for caption support)

Use the "core" version of video.js

---

src/components/bars/action.js
src/components/bars/index.scss
src/components/bars/navigation.js
src/components/index.scss
src/components/utils/button/index.scss
src/components/video/index.scss
src/config.json
src/styles/colors.css

- Update background colour to background-color: rgb(243, 246, 249);
- With updating the background colour to use the lighter grey,
we’ll need to update the text and stand alone icon colours to
use color: rgb(78, 90, 102);
- Update slides button to use the full blue button colour;
- Update the “-” icon to be a left chevron “<” to close the left
panel and a right chevron “>” to open the left panel;
- Center the “play button” to be in middle of the browser;
- Hide the search button until the experience is more robust - we
believe the current implementation may drive an increase in
support tickets;
- Move the swap button to the left hand side in replace of the
search button.

Add new design

---

src/components/bars/action.js
src/components/index.scss
src/components/player.js
src/components/presentation/slide.js
src/components/thumbnails/index.js
src/components/thumbnails/index.scss
src/config.json
src/locales/messages/ar.json
src/locales/messages/de.json
src/locales/messages/en.json
src/locales/messages/es.json
src/locales/messages/fr.json
src/locales/messages/it.json
src/locales/messages/ja.json
src/locales/messages/pt.json
src/locales/messages/ru.json
src/styles/colors.css
src/styles/sizes.scss
src/utils/data.js

Replaces the toggle button for a content bottom inline thumbnails' view.
This change also includes an automated horizontal scroll and still maintain
the thumbnails' keyboard shortcut.
Closes #63 .

Inline thumbnail experience

---

src/components/bars/action.js
src/components/index.scss
src/components/loader.js
src/components/player.js
src/utils/builder.js
src/utils/data.js

This work is a starting point for building a more dynamic and automatic layout
for the recording's playback.
This first idea is to provide a better space usage for recordings that do
not provide presentation related data, such as slides, annotations, cursor
and panzooms nor screenshare (which occupies the same location at the playback).
To use this option in custom builds and avoid the playback trying to fetch for
files that will never exist in a recording, the missing files can be removed
from files.data at config.json.
e.g. for a webcams with closed captions and chat case:
```
...
"files": {
"data": {
"captions": "captions.json",
"chat": "slides_new.xml",
"metadata": "metadata.xml"
},
...
```
Related with #15.

Dynamic layout

---

src/components/thumbnails/index.js
src/components/thumbnails/index.scss
src/styles/images.scss

This includes the missing logo background image to the thumbnails. Usually
the logo slide occurs when the meeting is defined as autoStartRecordng.
Closes #73 .

Add logo thumbnail

---

src/components/chat/index.scss

When an user had a long name all the data inside the chat message was being
pushed out of the application's container. This change set the style to avoid
overflowing this component data.
Closes #82 .

Hide chat data overflow

---

README.md
src/utils/data.js

Hey!
We intent to deploy `bbb-playback` on a separate server from where the medias will be stored. We needed an option to load medias from somewhere else than the default location. We though this feature could be useful for others too.
Let me know what you think!

Allow loading media from a different path or an external URL

---

src/components/error.js
src/components/loader.js

Fixes an error where the router was not able to render the generic error page because `intl` was missing. This happens on routing errors for example when the `meetingId` is completely missing.
Before:
After:
Note that I'm not well versed in the subtleties of React. There may be a better fix.

Fix TypeError: Cannot read property 'formatMessage' of undefined

---

src/components/chat/index.js
src/components/thumbnails/index.js

This change prevents auto scroll to force a position update while the
user has her/his mouse over the scrollable element.
Reported by @LLCarlos & @fcecagno

Avoid auto scroll while user interaction

---

README.md
src/utils/data.js

Hi!
I'm not sure this is an appropriate pull request, but since we needed to do it for us I figured it was probably worth a discussion anyway. This may not be a very popular use case, but we needed more flexibility regarding the assets path to the files of a recording.
We use the functionality documented in the README to specify external path for records. However, there are several places in the code that the player builds a file path using the informations stored within medadata.
In our case, the user accesses the player via
http://example.org/playback/presentation/2.3/{meetingId}
However, the recordings in our app are splitted into different folders depending on the tenant to avoid listing all the recordings within the same folder. When the player rebuilds the file urls strictly …

Add mediaPath parameter in order to be able to specify assets folder

---

src/utils/synchronizer.js

Blink based browsers pause the secondary media (screenshare) while the
document is not visible.
Add a seek-sync routine to be dispatched when the document's visibilityState
changes to visible.
Closes #74

fix(synchronizer): media sync on visible

---

src/components/webcams/index.js
src/utils/data/storage.js

EXPERIMENTAL: pre-v2.2 BigBlueButton could generate audio-only
recordings. This changes add support for webm containers for such
recordings.
TODO: add support for mp3 audio-only recordings.
Closes #112

feat(media): fallback audio support

---

src/utils/builder.js

Add empty canvases to listen for all slide changes and avoid carrying
the previous slide annotations to the following one.

fix(canvases): empty canvas force clean

---

README.md
src/components/webcams/index.js
src/utils/params.js

Add new `f` query string param to control the player renders' frequency
per run. This is useful for profiling performance without rebuilding the
app.

feat(params): render frequency control

---

src/components/webcams/index.js

Add a `seeked` event listener at the primary media to force update the
player's data when the media is paused.
Closes #160

fix(player): update data on media seeked

---

src/components/player/buttons/index.scss

This patch fixes the problem reported in #166 and #103.
As far as I understand, it's a problem from video.js, not from bbb-playback. 
This PR may offer a decent workaround until the problem is fixed in the video.js side.
.

Fix mispositioned caption popup

---

src/components/bars/top/buttons/theme.js

Avoid replacing the annotation colors when the dark mode is enabled.
Closes #192

fix(canvas): preserve annotation colors

---

src/index.js

Since version of react has been bumped upto 18, therefore change to
New Root API is required.
https://github.com/reactwg/react-18/discussions/5

Replace ReactDOM.render with createRoot

---

package-lock.json
package.json
src/components/tldraw/index.js
src/components/tldraw/index.scss
src/utils/builder.js

- Uses the updated pan&zoom event (https://github.com/bigbluebutton/bigbluebutton/pull/15583) to only show the portion of the slide according to the viewbox
- Update tldraw version
- Don't allow pan&zoom and hovering/selecting on itens
- Hide context menu (right click)
Need the updated pan&zoom event from:
https://github.com/bigbluebutton/bigbluebutton/pull/15583
Closes #210

fix(tldraw): respect view area width/height +

---

src/components/tldraw/index.js

Decrease background slide index so other shapes can't be hidden behind it.

fix(tldraw): moved to back shapes lost behind slide

---

src/components/tldraw/index.scss

decrease tldraw zindex so it statys behind video controls
Before:
After:

fix(tldraw): video tooltips/volume behind presentation

---

package-lock.json
package.json

Matching the version of the client, upgraded via https://github.com/bigbluebutton/bigbluebutton/pull/16487

chore: bump tldraw to 1.27.0 to match client

---

src/components/chat/messages/user/text.js

This patch introduces a space before URL in chat messages only when there is no space there.
It improves how the link is displayed during the playback, especially when Japanese (or maybe other Asian letters) text is combined.
Here is the closed issue report that I mistakenly posted on BigBlueButton project:
https://github.com/bigbluebutton/bigbluebutton/issues/18313

Put a space before URL in chat messages

---

src/components/tldraw/index.js

This fixes the whiteboard annotations to be displayed only in the slides they were made.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/18721
To test this PR, one can run the `./deploy.sh` [script](https://github.com/bigbluebutton/bbb-playback/blob/develop/deploy.sh) which will make a bundle out of the playback folder and place it in the correct directory. Despite this comfort automated script's build, the last part of it must be commented out because, since there is already an NGINX file correctly configured for playback in `/usr/share/bigbluebutton/nginx/playback.nginx`, and so if the last part of the script runs, it will also place the NGINX configuration file in `/etc/bigbluebutton/nginx/playback.nginx` which will crash NGINX. Hence, the `deploy.sh` will look like the …

fix: whiteboard annotations appearing in all slides.
